-- MySQL Script generated by MySQL Workbench
-- Mon May 15 20:32:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`role` ;
CREATE TABLE `mydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO `role` ( `role`) VALUES
('ROLE_ADMIN'),
('ROLE_USER');
-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `idusers` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(45) NOT NULL,
  `enabled` bool NOT NULL,
  `role_id` INT DEFAULT NULL,
  INDEX `fk_rent_user_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  PRIMARY KEY (`idusers`))
ENGINE = InnoDB;

insert into `users` values(null,'admin','admin','admin','$2a$10$TJ67btrXLLt4mrsqY6pYBuohGTPDMR.REbtmPBoHI3KY5a9EQIyTy', 'admin@admin.pl', 1, 1);
insert into `users` values(null, 'user', 'user', 'user', '$2a$10$FTGD71RyXUsSqH1TuwWwt.GZFa/pUAlXGYC2VxEbsv92OZuVntNBu', 'test@test.pl', 1, 2);

-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `idcar` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `available` BOOL NOT NULL,
  PRIMARY KEY (`idcar`),
  UNIQUE INDEX `idcar_UNIQUE` (`idcar` ASC))
ENGINE = InnoDB;

insert into `car` values(null, 'Porshe', '711', true);
insert into `car` values(null, 'Lamborgini', 'Gallardo', true);
insert into `car` values(null, 'Ferrari' , 'California', false);

-- -----------------------------------------------------
-- Table `mydb`.`rent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rent` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rent` (
  `idrent` INT NOT NULL AUTO_INCREMENT,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `users_idusers` INT NOT NULL,
  `car_idcar` INT NOT NULL,
  PRIMARY KEY (`idrent`),
  UNIQUE INDEX `idrent_UNIQUE` (`idrent` ASC),
  UNIQUE INDEX `start_UNIQUE` (`start` ASC),
  INDEX `fk_rent_users_idx` (`users_idusers` ASC),
  INDEX `fk_rent_car1_idx` (`car_idcar` ASC),
  CONSTRAINT `fk_rent_users`
    FOREIGN KEY (`users_idusers`)
    REFERENCES `mydb`.`users` (`idusers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rent_car1`
    FOREIGN KEY (`car_idcar`)
    REFERENCES `mydb`.`car` (`idcar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

insert into `rent` values(null, '2017-05-21 22:46:35', NULL, 2, 3);
insert into `rent` values(null, '2017-05-21 23:46:35',  '2017-05-21 23:50:35', 2, 2);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
